gitignore barcode.weights, BACKEND_OPENCV, vehicle.launch remap fixed…
mhkabir/dnn_detector pull request #1
Opened 2018-09-26 22:29 UTC by jonathan7

.gitignore: added barcode.weights
launch/vehicle.launch: fixed mappings
CMakeLists.txt: added includes
src/dnn_detector.cpp: switch to BACKEND_OPENCV

2018-09-26 23:48 UTC, mhkabir requested changes

2018-09-26 23:48 UTC, mhkabir commented on CMakeLists.txt
> +  /home/kabir/catkin_ws/src/image_processing/image_common/image_transport/include
Wrong fix. This needs to be a dependency in the catkin_package() call.

2018-09-26 23:48 UTC, mhkabir commented on src/dnn_detector.cpp
> +    network_.setPreferableBackend(cv::dnn::DNN_BACKEND_OPENCV);
Not sure if I want to accept this. It's a workaround.

2020-05-01 05:43 UTC, jonathan7 commented
not sure why this showed up in my "pull requests" view, lol

2020-05-01 05:43 UTC, closed without merging